pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Uthayan45/EcommerceAutomation.git'
            }
        }

        stage('Build and Test') {
            steps {
                bat 'mvn clean test'
            }
        }
    }
}
